pipeline {
    agent any
    tools {
        maven 'localMaven'
        jdk 'localJava'
    }
    stages {
    
        stage ('Build') {
            steps {
            bat 'mvn -f AtelierAgl/pom.xml install'
            }
           
     }
     
  

}
}